#ifndef USER_SETUP_LOADED
#define USER_SETUP_LOADED

#define USER_SETUP_INFO "ESP32-2432S028R WiFi Radar V2"
#define ILI9341_2_DRIVER
#define TFT_RGB_ORDER TFT_RGB
#define TFT_INVERSION_ON

#define TFT_WIDTH 240
#define TFT_HEIGHT 320
#define TFT_MISO 12
#define TFT_MOSI 13
#define TFT_SCLK 14
#define TFT_CS 15
#define TFT_DC 2
#define TFT_RST -1
#define TFT_BL 21
#define TOUCH_CS 33
#define TFT_BACKLIGHT_ON HIGH
#define USE_HSPI_PORT

#define LOAD_GLCD
#define LOAD_FONT2
#define LOAD_FONT4

#define SPI_FREQUENCY 40000000
#define SPI_READ_FREQUENCY 20000000
#define SPI_TOUCH_FREQUENCY 2500000

#endif
